---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages for Kubernetes repo
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg

- name: Create keyrings directory for Kubernetes apt repo
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Download Kubernetes apt GPG key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.33/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
  register: k8s_gpg_key

- name: Convert GPG key to dearmor format
  ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /etc/apt/keyrings/kubernetes-apt-keyring.asc
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  when: k8s_gpg_key.changed

- name: Add Kubernetes apt repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.33/deb/ /
    owner: root
    group: root
    mode: '0644'

- name: Install kubelet, kubeadm, and kubectl
  ansible.builtin.apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: true

- name: Hold kubelet, kubeadm, and kubectl
  ansible.builtin.command:
    cmd: apt-mark hold kubelet kubeadm kubectl

- name: Enable and start kubelet service
  ansible.builtin.systemd:
    name: kubelet
    enabled: true
    state: started

- name: Initialize Kubernetes Control Plane with containerd
  ansible.builtin.command:
    cmd: kubeadm init --cri-socket unix:///var/run/containerd/containerd.sock
    creates: /etc/kubernetes/admin.conf
