---
- name: Set sysctl parameters for Kubernetes networking
  ansible.builtin.lineinfile:
    create: true
    group: root
    line: 'net.ipv4.ip_forward = 1'
    mode: '0644'
    owner: root
    path: /etc/sysctl.d/k8s.conf

- name: Ensure net.ipv4.ip_forward is set
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    sysctl_file: /etc/sysctl.d/k8s.conf
    value: '1'

- name: Install Containerd
  ansible.builtin.apt:
    name: containerd
    update_cache: true
  tags: ['containerd']

- name: Create containerd config directory
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Generate default containerd config
  ansible.builtin.command:
    cmd: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Write Container Runtime default config to /etc/containerd/config.toml
  ansible.builtin.copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_default_config.stdout }}"
    owner: root
    group: root
    mode: '0644'

- name: Set SystemdCgroup to true
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'

- name: Set sandbox_image to registry.k8s.io/pause:3.10
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    regexp: '^(\s*sandbox_image\s*=\s*).*$'
    replace: '\1"registry.k8s.io/pause:3.10"'

- name: Restart containerd
  ansible.builtin.service:
    name: containerd
    state: restarted
